#!/bin/bash

pwd

echo "Running pre-commit hook..."

function header {
	echo "================================================================================"
	echo $1
	echo "================================================================================"
}

function stop {
	if [[ $? != 0 ]]; then
		echo "EXIT"
		exit 1
	fi
}

header "Checking composer.json normalization"
composer normalize --dry-run --indent-size=1 --indent-style=tab
stop

header "Checking PHP syntax with PHP-CS-Fixer"
vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
stop

header "Checking for PHP errors"
php -l src/*
stop
php -l tests/*
stop

header "Analysing code with PHPStan"
vendor/bin/phpstan analyse
stop

header "Detecting code messes with PHPMD"
vendor/bin/phpmd src/ text phpmd.xml
stop
vendor/bin/phpmd tests/ text phpmd.xml
stop

header "Testing with PHPUnit"
vendor/bin/phpunit
stop

echo
echo "OK. Commit status:"
